# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "852b805337abed14360a3803dacf48d2"
name = "Returns Hub"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "returns/request" ]
  uri = "/webhooks/returns/request"

  [[webhooks.subscriptions]]
  topics = [ "returns/approve" ]
  uri = "/webhooks/returns/approve"

  [[webhooks.subscriptions]]
  topics = [ "returns/decline" ]
  uri = "/webhooks/returns/decline"

  [[webhooks.subscriptions]]
  topics = [ "returns/close" ]
  uri = "/webhooks/returns/close"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_fulfillments,read_orders,read_products,read_returns,write_fulfillments,write_orders,write_returns"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
